import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [file, setFile] = useState(null);
  const [imgSrc, setImgSrc] = useState(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = (e) => {
    e.preventDefault();
    setIsLoading(true);

    const formData = new FormData();
    formData.append('file', file);

    fetch(`/api/convert/${window.location.host}`, {
      method: 'POST',
      body: formData,
    })
      .then((res) => res.json())
      .then((res) => {
        setImgSrc(res.converted);
        setIsLoading(false);
      })
      .catch((_) => {
        alert('File Upload error!');
      });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>Word To Image</p>

        <section className={styles.section}>
          <form method='post' onSubmit={handleSubmit}>
            <label htmlFor='img' className={styles.label}>
              Select image:
            </label>
            <input
              type='file'
              name='img'
              accept='.doc, .docx'
              required
              multiple
              className={styles.fileUpload}
              onChange={(e) => setFile(e.target.files[0])}
            />
            <button className={styles.button} disabled={isLoading}>
              {isLoading ? 'Converting' : 'Submit'}
            </button>
          </form>

          {imgSrc && (
            <Image
              src={imgSrc}
              height={350}
              width={350}
              alt='uploads'
              className={styles.img}
            />
          )}
        </section>
      </main>
    </div>
  );
}
